version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: test_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"  # Maps container's 5432 to host's 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
