spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/test_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always
server:
  port: 8020
